---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 11.0.2-jdk-stretch

inputs:
  - name: source

caches:
  - path: .gradle/

params:
  SPRING_CLOUD_GCP_PUBSUB_PROJECT_ID:
  SPRING_CLOUD_GCP_PUBSUB_CREDENTIALS_ENCODED_KEY:

run:
  path: source/pipeline/scripts/build.sh
