---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 11.0.2-jdk-stretch

inputs:
- name: source

caches:
- path: source/.gradle/

params:
  GCE_METADATA_HOST: 169.254.169.254

run:
  path: bash
  dir: source
  args:
  - -ec
  - ./gradlew build --no-daemon
