---
groups:
- name: all
  jobs:
  - build
  - major
  - minor
  - release
- name: develop
  jobs:
  - build
- name: release
  jobs:
  - major
  - minor
  - release

jobs:

- name: build
  plan:
  - get: once-per-weekday
    trigger: true
  - get: source
    trigger: true
  - task: build
    file: source/pipeline/tasks/build.yaml

- name: major
  plan:
  - put: version
    params:
      bump: major
      pre: dev

- name: minor
  plan:
  - put: version
    params:
      bump: minor
      pre: dev

- name: release
  plan:
  - get: source
    passed: [build]
  - get: version
    params:
      bump: final
  - put: source
    params:
      repository: source
      tag: version/version
      only_tag: true
  - put: version
    params:
      bump: patch

resources:

- name: source
  type: git
  icon: github
  source:
    branch: master
    private_key: ((event-bus.repo-key))
    uri: git@github.com:boclips/event-bus.git

- name: once-per-weekday
  type: time
  icon: clock
  source:
    start: "08:30"
    stop: "20:00"
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    location: Europe/London

- name: version
  type: semver
  icon: github
  source:
    initial_version: "0.1.0"
    driver: git
    uri: git@github.com:boclips/versions.git
    branch: master
    file: event-bus
    private_key: ((versions.repo-key))
